X(DELAY_EQ_0, (max(1, (params.ny)) + -1))
X(DELAY_EQ_1, (max(1, min(((1 + (-1 * (params.ny))) + (params.nzy)), 91)) + -1))
X(DELAY_EQ_2, (max(1, min((params.nzy), 100)) + -1))
X(CE_DELAY_EQ_0, ((114 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_1, ((114 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_2, ((114 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_3, ((114 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_4, ((110 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_5, ((114 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_6, ((111 + (-1 * (params.ny))) + (-1 * (params.nzy))))
X(CE_DELAY_EQ_7, ((111 + (-1 * (params.ny))) + (-1 * (params.nzy))))
